FROM ubuntu:20.04

# disable linux interactive requests
ENV DEBIAN_FRONTEND=noninteractive

# install node
RUN apt-get update && apt-get -y install nodejs npm

# install libreoffice
RUN apt-get update && apt-get install -y libreoffice

# install preview dependencies (https://www.npmjs.com/package/filepreview-es6)
RUN apt-get update && apt-get install -y unoconv ffmpeg imagemagick curl

# fix pdf security rule from imagemagick
RUN sed -i 's/<\/policymap>/  <policy domain="coder" rights="read | write" pattern="PDF" \/>\
<\/policymap>/g' /etc/ImageMagick-6/policy.xml

# Create app directory
RUN mkdir /app

WORKDIR /app

# update npm
RUN npm i -g npm@latest

# Copy application in the container
ADD . .

# Install app dependencies
RUN npm install

# Build application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Run application
CMD [ "npm", "run", "start" ]