FROM node:14.11.0

# Create app directory
RUN mkdir /app
WORKDIR /app

# Copy application in the container
COPY . .

# Install app dependencies
RUN npm install

# Build application
RUN npm build

# Delete sources
RUN rm -rf src/
RUN rm nodemon.json
RUN rm tsconfig.json
RUN rm .gitignore
RUN rm .eslintignore
RUN rm .eslintrc

# Expose port 3000
EXPOSE 3000

# Run application
CMD [ "npm", "run", "start" ]