
/*
Autogenerated file.
Do not directly edit
See frontend/scripts/setenv.ts
*/
export const environment = {
  production: false,
  apiBaseURL: 'http://localhost:3000',
  etherpadBaseUrl: 'none',
  authCookieDomain: 'localhost',
  authCookieName: 'access_token',
  userLocalStorageKey: 'real_user',
  disableStripe: true,
  disableTwoFactorAuthAndEmail: true,
  disableEtherpad: true,
  stripePublicKey: 'none',
}
