/*
Autogenerated file.
Do not directly edit
See frontend/scripts/setenv.ts
*/
export const environment = {
  production: true,
  apiBaseURL: 'http://localhost:3000',
  etherpadBaseUrl: 'http://localhost:9001',
  authCookieDomain: 'localhost',
  authCookieName: 'access_token',
  userLocalStorageKey: 'real_user',
  stripePublicKey: 'pk_test_XXX',
};