
/*
Autogenerated file.
Do not directly edit
See frontend/scripts/setenv.ts
*/
export const environment = {
  production: false,
  apiBaseURL: 'http://localhost:3000',
  etherpadBaseUrl: 'http://192.168.56.1:9001',
  authCookieDomain: 'localhost',
  authCookieName: 'access_token',
  userLocalStorageKey: 'real_user',
  disableStripe: false,
  stripePublicKey: 'pk_test_XXX',
};
