FROM node:alpine

RUN npm install -g redoc-cli@0.9.11

WORKDIR /data
ADD swagger.yml ./swagger.yml
#RUN redoc-cli --help
RUN redoc-cli bundle ./swagger.yml

# change of route

FROM nginx

COPY --from=0 /data/redoc-static.html /usr/share/nginx/html/index.html
RUN ls /usr/share/nginx/html
